{% set name = "pydecorate" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe0dd3ee57ec6b130ecfea016e93b37fbcf1ebe7b0ae1af5ff1807066c4de27d

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.6
    - pillow
    - aggdraw
    - numpy

test:
  imports:
    - pydecorate

about:
  home: https://github.com/pytroll/pydecorate
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: 'Decorating PIL images: logos, texts, pallettes'
  doc_url: https://pydecorate.readthedocs.io/en/latest/
  dev_url: https://github.com/pytroll/pydecorate

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - pnuu
    - adybbroe
