{% set name = "pydecorate" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8e1549779fc31311ae2697b33587ff05eb56cdb39a8a36ed2074b34443715339

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.7
    - pillow
    - aggdraw
    - numpy
    - setuptools

test:
  imports:
    - pydecorate

about:
  home: https://github.com/pytroll/pydecorate
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: 'Decorating PIL images: logos, texts, pallettes'
  doc_url: https://pydecorate.readthedocs.io/en/latest/
  dev_url: https://github.com/pytroll/pydecorate

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - pnuu
    - adybbroe
