{% set name = "pydecorate" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5110be42f0f2a58e2b1ea22ac6838b47f021402cf79fa0ec911ce7fb4243e54d

build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.6
    - pillow
    - aggdraw
    - numpy

test:
  imports:
    - pydecorate

about:
  home: https://github.com/pytroll/pydecorate
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: 'Decorating PIL images: logos, texts, pallettes'
  doc_url: https://pydecorate.readthedocs.io/en/latest/
  dev_url: https://github.com/pytroll/pydecorate

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - pnuu
    - adybbroe
