{% set name = "pydecorate" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ea96cf530aecbb5c22e84d1e83c9d9035465f4c59e905277904d0c9641b6dbc6

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - pillow
    - aggdraw
    - numpy
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - pydecorate

about:
  home: https://github.com/pytroll/pydecorate
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Decorating PIL images: logos, texts, pallettes'
  doc_url: https://pydecorate.readthedocs.io/en/latest/
  dev_url: https://github.com/pytroll/pydecorate

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - pnuu
    - adybbroe
