{% set name = "pydecorate" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c75c4db54132d9b97dd328a693670cd1457c416143a893d92286544e46762ae9

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.9
    - pillow
    - aggdraw
    - numpy
    - setuptools

test:
  imports:
    - pydecorate

about:
  home: https://github.com/pytroll/pydecorate
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: 'Decorating PIL images: logos, texts, pallettes'
  doc_url: https://pydecorate.readthedocs.io/en/latest/
  dev_url: https://github.com/pytroll/pydecorate

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - pnuu
    - adybbroe
