{% set name = "pydecorate" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5296b698cca156fa672ed166087bb5d21b23a72c69cd45f65e6d71c32cb13caf

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pillow
    - aggdraw
    - numpy

test:
  imports:
    - pydecorate

about:
  home: https://github.com/pytroll/pydecorate
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE.txt
  summary: 'Decorating PIL images: logos, texts, pallettes'
  doc_url: https://pydecorate.readthedocs.io/en/latest/
  dev_url: https://github.com/pytroll/pydecorate

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - pnuu
    - adybbroe
