travis:
  secure:
    BINSTAR_TOKEN: GyX9AJSVwIiuW3iEujqHY5oNJo4HgeiSi2jxVSCTmUhyA/IDX0oEokDgPoTCTqPIl65xQMjZJXR/oLkuRNXIgx5gqIIT0ynIhmgiTOAT7ECZCQ7bfBogUSfXNayhRrnjikKlUz9Vl6ZUOeJTyqHI6zptYykuEU8FtSvEe7fv+HCfbnXCj37yNW0ixaxLdSmJAHcK1YRwJdyi2YD0p4xl8lzeLJm2eHMd7AhMWuoYnpiAJ8/MbIutyEWF97B5YVsqj0s8si8NmuAdbzIZM8rzkPqmtdTuXs8Oh5mcIFfk/SI0idq2qxL9vTpv+CLX7M+Rk/Pp1qloBQ4pHjiEEH1+rafb+7UFZHpBNeOsdFRfJZSTvC9WzXuNFNXOJyOHY6Di/hUMlBSJWjqaxgrGXqzY+kfZqnJdwDNKmKnyNUJxV7GIFY7ty4ZO7eBNcf2D0YQ8r/JN5848bj/X1oJC/XGTe+0OtUPDPblOy2Z2D5ERQcPV/vR/kAgn+KCjSC4KWkbXk7ij//TLlajgdoYeRuOrjcL14wpIWm35p9N05p7XNn8X7SOV0Ps9mkntjlajhgTEZc2s3YTyv4XYRnRQsu/XS3AHrV/cQr/hFAo2iZl3Lyrys2p0klG2Qc5BjsWc+m64jKnsw++t0fv2YVAmZ8tG7U9lF3gGFv2g/ewCcqJlf8Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
