travis:
  secure:
    BINSTAR_TOKEN: Q4Jvmi33ieipCVrc78bY7wZsrAvDBY1ghgbUMtaPD8ic0DxU3gAQxYNUI9K2pO5ThlgkkJtm9y0vcNcjtzcqV0dyjgxQFsMbboFqQtR8+DjR2Fgiw81t3sxg3tHskxZ5y7HXCemEM65MYZlTU74FQ61iutjea294cv46anxiQlR1b8hY20qQiC3nCF5FrmuQf/+5kWCbf876fpvVgfJCk5SrRUSXPFgIOWTfoykinFll/J1w9MDVkZ1JvJxowy9KZtWxqcFbYi12QqmRbkICEHWYsdrYhkp8sp7s7AALQSmv7QBnX4t9HjuRAFAqws8wgOOla1u6pXqh/L2J7XgIlSZA8JFqAXLczknTOPcxEnqFcE5Rpgx9ZYxEu4NyjulMavydCDFYGMAO1PbV+PoMf52fs91+ZD6rpE3zUPjj9yEQsll1027N0Q4IR0DQCbF+WdalW7U7hPlxyFre5ppaDau1Qo9uHyi48Wws5WTfPLd0c+UnunGUhrE4mvxTTiAtyULjF6vyBIC+5sJ9yRLS6JbJffKvMOvHKR4ThdTazcG6eDC62eknIhPnvY35mA4QKI7MXzMBjBbSQLl3bi41fJBNneFLaRkHGApjOsltfGkE3teAaO76XJKn3P5Ar8mB9dmz7xPvsJssDyBmTXIAOeMremHvkDCmbevUtz2JthA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
